Revert "Un-xfail swiftpm-test.test for main"
This reverts commit 9e708855fca0f49303292e911a8cdfac41f71047.

Hmm, it's still failing

```
/tmp/swift-extra-integration-tests/toolchain/Output/swiftpm-test.test.tmp.dir/.build/wasm32-unknown-wasi/debug/ExamplePackageTests.derived/runner-XCTest.swift:402:42: error: value of type 'Bundle' has no member 'bundleIdentifier'
400 │     init(_ testBundle: Bundle) {
401 │         self.init(
402 │             bundleIdentifier: testBundle.bundleIdentifier,
    │                                          ╰─ error: value of type 'Bundle' has no member 'bundleIdentifier'
403 │             bundlePath: testBundle.bundlePath
404 │         )
```